---

- name: "Add UFW to host"
  ansible.builtin.package:
    pkg:
    - ufw
  register: package_status
  when: ufw_enabled | bool
  until: package_status is success
  delay: 6
  retries: 10

- name: "Set up UFW rules from dictionary (If ufw_enabled is true and ufw_allow_dict is not '{}')"
  community.general.ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('any') }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    insert_relative_to: "{{ item.insert_relative_to | default('zero') }}"
    direction: "{{ item.direction | default('in') }}"
  loop: "{{ ufw_allow_dict }}"
  when: ( ufw_enabled | bool ) and ( ufw_allow_dict | length > 0 )

- name: "UFW default allow outgoing traffic on host"
  community.general.ufw:
    policy: allow
    direction: outgoing
  when: ufw_enabled | bool

- name: "UFW default deny incoming traffic on host"
  community.general.ufw:
    policy: deny
    direction: incoming
  when: ufw_enabled | bool

- name: "Enable Firewall on host"
  community.general.ufw:
    state: enabled
  when: ufw_enabled | bool
